name: github-actions
run-name: ${{ github.actor }} is testing GitHub Actions
on: [push]
jobs:
  compile_timing_app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: install necessary packages for openGL
        run: |
          apt-get install freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libglfw3-dev
      - name: install GLFW package
        run: apt-get install libglfw3-dev
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: create a build directory
        run: mkdir ${{ github.workspace }}/build
      - name: generate cmake code
        run: cmake -S ${{ github.workspace }} -B ${{ github.workspace }}/build
      - run: cd ${{ github.workspace }}/build
      - run: make
      - name: check timing version
        run: ${{ github.workspace }}/build/timing -v
# need c++ compiler?: apt-get install g++